// ------------
// structures
// ------------

#ifdef GLOBAL_NAMESPACE
auto ann_ImDrawData = make_smart<ImDrawData_GeneratedAnnotation>(lib);
addAnnotation(ann_ImDrawData);
#endif
#ifdef IMNODES_NAMESPACE
auto ann_Style = make_smart<Style_GeneratedAnnotation>(lib);
addAnnotation(ann_Style);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImFontGlyphRangesBuilder = make_smart<ImFontGlyphRangesBuilder_GeneratedAnnotation>(lib);
addAnnotation(ann_ImFontGlyphRangesBuilder);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiPayload = make_smart<ImGuiPayload_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiPayload);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiStoragePair = make_smart<ImGuiStoragePair_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiStoragePair);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImFontConfig = make_smart<ImFontConfig_GeneratedAnnotation>(lib);
addAnnotation(ann_ImFontConfig);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiIO = make_smart<ImGuiIO_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiIO);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImNewWrapper = make_smart<ImNewWrapper_GeneratedAnnotation>(lib);
addAnnotation(ann_ImNewWrapper);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImDrawVert = make_smart<ImDrawVert_GeneratedAnnotation>(lib);
addAnnotation(ann_ImDrawVert);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiTableSortSpecs = make_smart<ImGuiTableSortSpecs_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiTableSortSpecs);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImDrawCmdHeader = make_smart<ImDrawCmdHeader_GeneratedAnnotation>(lib);
addAnnotation(ann_ImDrawCmdHeader);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImFontGlyph = make_smart<ImFontGlyph_GeneratedAnnotation>(lib);
addAnnotation(ann_ImFontGlyph);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImFontAtlas = make_smart<ImFontAtlas_GeneratedAnnotation>(lib);
addAnnotation(ann_ImFontAtlas);
#endif
#ifdef IMNODES_NAMESPACE
auto ann_IO = make_smart<IO_GeneratedAnnotation>(lib);
addAnnotation(ann_IO);
#endif
#ifdef IMNODES_NAMESPACE
auto ann_EmulateThreeButtonMouse = make_smart<EmulateThreeButtonMouse_GeneratedAnnotation>(lib);
addAnnotation(ann_EmulateThreeButtonMouse);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiOnceUponAFrame = make_smart<ImGuiOnceUponAFrame_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiOnceUponAFrame);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiTextFilter = make_smart<ImGuiTextFilter_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiTextFilter);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiSizeCallbackData = make_smart<ImGuiSizeCallbackData_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiSizeCallbackData);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiListClipper = make_smart<ImGuiListClipper_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiListClipper);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImFont = make_smart<ImFont_GeneratedAnnotation>(lib);
addAnnotation(ann_ImFont);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiTextBuffer = make_smart<ImGuiTextBuffer_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiTextBuffer);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiInputTextCallbackData = make_smart<ImGuiInputTextCallbackData_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiInputTextCallbackData);
#endif
#ifdef IMNODES_NAMESPACE
auto ann_LinkDetachWithModifierClick = make_smart<LinkDetachWithModifierClick_GeneratedAnnotation>(lib);
addAnnotation(ann_LinkDetachWithModifierClick);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImDrawCmd = make_smart<ImDrawCmd_GeneratedAnnotation>(lib);
addAnnotation(ann_ImDrawCmd);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiViewport = make_smart<ImGuiViewport_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiViewport);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImFontAtlasCustomRect = make_smart<ImFontAtlasCustomRect_GeneratedAnnotation>(lib);
addAnnotation(ann_ImFontAtlasCustomRect);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiStyle = make_smart<ImGuiStyle_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiStyle);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImDrawListSplitter = make_smart<ImDrawListSplitter_GeneratedAnnotation>(lib);
addAnnotation(ann_ImDrawListSplitter);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiStorage = make_smart<ImGuiStorage_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiStorage);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiTextRange = make_smart<ImGuiTextRange_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiTextRange);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImGuiTableColumnSortSpecs = make_smart<ImGuiTableColumnSortSpecs_GeneratedAnnotation>(lib);
addAnnotation(ann_ImGuiTableColumnSortSpecs);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImDrawChannel = make_smart<ImDrawChannel_GeneratedAnnotation>(lib);
addAnnotation(ann_ImDrawChannel);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_ImDrawList = make_smart<ImDrawList_GeneratedAnnotation>(lib);
addAnnotation(ann_ImDrawList);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImDrawData,lib);
#endif
#ifdef IMNODES_NAMESPACE
initRecAnnotation(ann_Style,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImFontGlyphRangesBuilder,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiPayload,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiStoragePair,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImFontConfig,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiIO,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImNewWrapper,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImDrawVert,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiTableSortSpecs,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImDrawCmdHeader,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImFontGlyph,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImFontAtlas,lib);
#endif
#ifdef IMNODES_NAMESPACE
initRecAnnotation(ann_IO,lib);
#endif
#ifdef IMNODES_NAMESPACE
initRecAnnotation(ann_EmulateThreeButtonMouse,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiOnceUponAFrame,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiTextFilter,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiSizeCallbackData,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiListClipper,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImFont,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiTextBuffer,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiInputTextCallbackData,lib);
#endif
#ifdef IMNODES_NAMESPACE
initRecAnnotation(ann_LinkDetachWithModifierClick,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImDrawCmd,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiViewport,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImFontAtlasCustomRect,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiStyle,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImDrawListSplitter,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiStorage,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiTextRange,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImGuiTableColumnSortSpecs,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImDrawChannel,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_ImDrawList,lib);
#endif

