// ------------
// enumerations
// ------------

addEnumeration(make_smart<EnumerationImGuiDataType_>());
addEnumeration(make_smart<EnumerationImGuiHoveredFlags_>());
addEnumeration(make_smart<EnumerationImGuiNavInput_>());
addEnumeration(make_smart<EnumerationImGuiDir_>());
addEnumeration(make_smart<EnumerationImGuiCond_>());
addEnumeration(make_smart<EnumerationImGuiDragDropFlags_>());
addEnumeration(make_smart<EnumerationImGuiColorEditFlags_>());
addEnumeration(make_smart<EnumerationImGuiWindowFlags_>());
addEnumeration(make_smart<EnumerationImGuiCol_>());
addEnumeration(make_smart<EnumerationImGuiTableFlags_>());
addEnumeration(make_smart<EnumerationImGuiKeyModFlags_>());
addEnumeration(make_smart<EnumerationImGuiFocusedFlags_>());
addEnumeration(make_smart<EnumerationImGuiMouseCursor_>());
addEnumeration(make_smart<EnumerationImDrawCornerFlags_>());
addEnumeration(make_smart<EnumerationImGuiTableBgTarget_>());
addEnumeration(make_smart<EnumerationImGuiButtonFlags_>());
addEnumeration(make_smart<EnumerationImGuiMouseButton_>());
addEnumeration(make_smart<EnumerationImGuiTabBarFlags_>());
addEnumeration(make_smart<EnumerationImGuiTreeNodeFlags_>());
addEnumeration(make_smart<EnumerationImGuiTabItemFlags_>());
addEnumeration(make_smart<EnumerationImDrawListFlags_>());
addEnumeration(make_smart<EnumerationImGuiSelectableFlags_>());
addEnumeration(make_smart<EnumerationImGuiTableColumnFlags_>());
addEnumeration(make_smart<EnumerationImGuiSortDirection_>());
addEnumeration(make_smart<EnumerationImGuiInputTextFlags_>());
addEnumeration(make_smart<EnumerationImGuiBackendFlags_>());
addEnumeration(make_smart<EnumerationImGuiPopupFlags_>());
addEnumeration(make_smart<EnumerationImGuiComboFlags_>());
addEnumeration(make_smart<EnumerationImGuiKey_>());
addEnumeration(make_smart<EnumerationImGuiStyleVar_>());
addEnumeration(make_smart<EnumerationImGuiConfigFlags_>());
addEnumeration(make_smart<EnumerationImGuiSliderFlags_>());
addEnumeration(make_smart<EnumerationImGuiTableRowFlags_>());
addEnumeration(make_smart<EnumerationImFontAtlasFlags_>());

